(function(){function fa(a,b){if(a)for(var c=B.parse(a+""),d=c[0].split(/\s*,\s*/),e=0;e<d.length;e++)b(B.stringify(d[e],c),e)}function ga(a,b){var c=this===window?document:this;return"string"==typeof a?b?ha.call(c.querySelectorAll(a),0):c.querySelector(a):a instanceof Node||a===window||!a.length?b?[a]:a:ha.call(a,0)}function g(a){if(a){for(var b in g.prototype)a[b]=g.prototype[b];return a}}function l(a,b,c,d){if(!a)return a;var e=a.on||a.addEventListener||a.addListener,f;f=d?l.wrap(c,d):c;b.split(/\s+/).forEach(function(b){if(e)if(ia.freeze(a,
"on"+b))e.call(a,b,f),ia.b(a,"on"+b);else return a;Ca.on.call(a,b,f)});return a}function N(a,b,c,d){return Da(a,b,N.wrap(a,b,c,d))}function r(a,b,c){if(!a)return a;var d;if(void 0===c){var e=Ea(arguments,1),f=a.removeAll||a.removeAllListeners;f&&f.apply(a,e);d=a.a;if(!d)return;if(b)b.split(/\s+/).forEach(function(b){if(d[b])for(var c=d[b].length;c--;)r(a,b,d[b][c])});else for(b in d)r(a,b);ja.off.apply(a,e);return a}var v=a.off||a.removeEventListener||a.removeListener;b.split(/\s+/).forEach(function(b){if(v)if(ka.freeze(a,
"off"+b))v.call(a,b,c),ka.b(a,"off"+b);else return a;ja.off.call(a,b,c)});return a}function la(a,b,c,d){var e,f=b;a.nodeType||a===Fa||a===Ga?(b instanceof Event?f=b:(f=document.createEvent("CustomEvent"),f.initCustomEvent(b,d,!0,c)),e=a.dispatchEvent):O&&a instanceof O?(f=O.Event(b,c),f.detail=c,e=d?targte.trigger:a.triggerHandler):e=a.emit||a.trigger||a.fire||a.dispatchEvent;f=[f].concat(ma(arguments,2));if(e&&na.freeze(a,"emit"+b))return e.apply(a,f),na.b(a,"emit"+b),a;Ha.c.apply(a,f);return a}
function P(a,b,c,d){return oa(a,b,P.wrap(a,b,c,d))}function Q(a,b,c,d){return pa(a,b,Q.wrap(a,b,c,d))}function R(a,b,c,d){return qa(a,b,R.wrap(a,b,c,d))}function S(a,b,c,d){return ra(a,b,S.wrap(a,b,c,d))}function C(a,b,c){if(a){var d=a.once||a.one||a.addOnceEventListener||a.addOnceListener,e;e=C.wrap(a,b,c,Ia);b.split(/\s+/).forEach(function(b){if(d&&sa.freeze(a,"one"+b)){var v=d.call(a,b,c);sa.b(a,"one"+b);return v}Ja(a,b,e)});return e}}function p(a){if(a){for(var b in w)a[b]=w[b];return a}}function F(a){return function(){a.apply(this,
[this].concat(Ka(arguments)));return this}}function x(a){return function(){a.apply(this,arguments);return this}}function ta(a,b){if(!b)return y(a)?a:[a];if(a===window)a===[T];else if(!La(a)&&!y(a))return[a];b=ua(a,b);var c,d,e=G.parse(b);if(c=/:(parent|closest|next|prev|root)(?:\\([0-9]+))?/.exec(e[0])){d=c[1];var f=c.index,v=G.stringify(e[c[2]],e);c=c[0];f&&(a=va(a,G.stringify(e[0].slice(0,f),e)));d=U(a,V[d],v);if(!d)return null;if(y(d)&&!d.length)return d;e=G.stringify(e[0].slice(f+c.length).trim(),
e);e=ua(d,e);d=ta(d,e)}else d=va(a,b);return d}function va(a,b){return y(a)?U(a,function(a,b){return ga.call(a,b,!0)},b):ga.call(a,b,!0)}function U(a,b,c){var d=[];y(a)||(a=[a]);for(var e=a.length,f;e--;)(f=a[e])&&(f=b(f,c))&&(d=[].concat(f,d));return d}function ua(a,b){if(!Ma(b))return b;b=b.trim();if(!wa){if(":scope"===b.slice(0,6))b=b.slice(6);else if(">"!==b[0])return b;var c=(1E9*Math.random()>>>0)+Na++;U(a,function(a,b){a.setAttribute("data-__qr",b);return a},c);b='[data-__qr="'+c+'"]'+b}else if(">"===
b[0])return":scope "+b;return b}function s(a){if(!a)return a;for(var b in D)a[b]=D[b];return a}function H(a,b){var c=b[0],d=b[1];Oa(d)||W(c)?(c=null,d=b[0],b=E(b,0)):b=E(b,1);if(d)if(b=E(b,1),d&&"object"===typeof d&&d.constructor===Object)for(var e in d)fa(e,function(b){H(a,[c,b].concat(d[b]))});else W(d)?fa(d,function(d){var e=I(d),h;h=c;e=e[0];h||(h=[document]);h=e?"window"===e?[window]:"document"===e?[document]:Pa(h,e,!0):Qa(h)?h:[h];for(var e=0,g=h.length;e<g;e++)a.apply(h[e],[h[e],d].concat(b))}):
a.apply(c,[c,d].concat(b))}function I(a){var b=["",""],c=a.match(/[\w\.\:\$\-]+(?:\:[\w\.\:\-\$]+(?:\(.+\))?)*$/)[0];b[0]=a.slice(0,-c.length).trim();a="on"===c.slice(0,2)?J(c.slice(2)):c;b[1]=a;return b}function Ra(a,b,c){if(c){var d=c,e=xa.parse(b);b=e[0].split(":");var f=b.shift();b.sort(function(a,b){return"once"===a||"one"===a?-1:"once"===b||"one"===b?1:0}).forEach(function(b){var h=b.split("\\");b=h[0];(h=xa.stringify(e[h[1]],e))||(h=function(a,b,d){X(a,b,d);X(a,b,c)});m[b]&&(d=m[b](a,f,d,h))});
return d}}window.Emitter=s;var z,u,J,K,A,n,ya,Y,q,k,B,t,Z,L;z=function(a){return"string"===typeof a||a instanceof String};u=function(a){return!(!a||!a.apply)};J=function(a){return a.toLowerCase()};g.prototype.on=g.prototype.addEventListener=function(a,b){this.a=this.a||{};(this.a[a]=this.a[a]||[]).push(b);return this};g.prototype.f=function(a,b){function c(){d.off(a,c);b.apply(this,arguments)}var d=this;this.a=this.a||{};c.fn=b;this.on(a,c);return this};g.prototype.off=g.prototype.removeListener=
g.prototype.removeEventListener=function(a,b){this.a=this.a||{};if(0==arguments.length)return this.a={},this;var c=this.a[a];if(!c)return this;if(1==arguments.length)return delete this.a[a],this;for(var d,e=0;e<c.length;e++)if(d=c[e],d===b||d.fn===b){c.splice(e,1);break}return this};g.prototype.c=function(a){this.a=this.a||{};var b=[].slice.call(arguments,1),c=this.a[a];if(c)for(var c=c.slice(0),d=0,e=c.length;d<e;++d)c[d].apply(this,b);return this};g.prototype.d=function(a){this.a=this.a||{};return this.a[a]||
[]};g.prototype.e=function(a){return!!this.d(a).length};K=function(a,b){if(a.contains)return a.contains(b);var c=a.compareDocumentPosition(b);return 0===c||c&16};J=function(a){return(a+"").toLowerCase()};"use strict";k=Element.prototype;var za=k.matches||k.matchesSelector||k.webkitMatchesSelector||k.mozMatchesSelector||k.msMatchesSelector||k.g;A=function(a,b){if(za)return za.call(a,b);for(var c=a.parentNode.querySelectorAll(b),d=0;d<c.length;d++)if(c[d]==a)return!0;return!1};n=function(a){return"undefined"!==
typeof document&&a instanceof Node};var ha=[].slice;(function(a){function b(a){for(var b=[],c=0;c<a.length;c++)-1===b.indexOf(a[c])&&b.push(a[c]);return b}function c(a){var b=new Set;return a.filter(function(a){if(!b.has(a))return b.add(a),!0})}function d(a){var b=[];(new Set(a)).forEach(function(a){b.push(a)});return b}function e(){var a=!1;(new Set([!0])).forEach(function(b){a=b});return a}ya="Set"in a?"function"===typeof Set.prototype.forEach&&e()?d:c:b}).call(this,"undefined"!==typeof global?
global:"undefined"!==typeof self?self:"undefined"!==typeof window?window:{});Y=function(a){return a instanceof Array};q={freeze:function(a,b){var c=M.get(a);if(c&&c[b])return!1;c||(c={},M.set(a,c));return c[b]=!0},b:function(a,b){var c=M.get(a);if(!c||!c[b])return!1;c[b]=null;return!0},isFrozen:function(a,b){var c=M.get(a);return c&&c[b]}};var M=new WeakMap;k=k=function(a,b,c){var d=[],e=a.length;if(0===e)return d;b=0>b?Math.max(0,b+e):b||0;for(void 0!==c&&(e=0>c?c+e:c);e-- >b;)d[e-b]=a[e];return d};
B={parse:function(a,b){function c(a){return"\\"+d.push(a.slice(1,-1))}if("string"!==typeof a)return[a];var d=[],e;b=b||"()";for(var f=new RegExp(["\\",b[0],"[^\\",b[0],"\\",b[1],"]*\\",b[1]].join(""));a!=e;)e=a,a=a.replace(f,c);d.unshift(a);return d},stringify:function(a,b,c){function d(a){return c[0]+b[a.slice(1)]+c[1]}var e;if(!a)return"";"string"!==typeof a&&(c=b,b=a,a=b[0]);for(c=c||"()";a!=e;)e=a,a=a.replace(/\\[0-9]+/,d);return a}};var aa=document,Sa=aa.documentElement;t=function(a,b){if(!n(a))throw Error("Bad argument "+
a);if(a===aa)return Sa;if(!b||(n(b)?a==b:A(a,b)))return a;for(;(a=a.parentNode)&&a!==aa;)if(!b||(n(b)?a==b:A(a,b)))return a};var ia=q,Ca=g.prototype;l.wrap=function(a,b,c,d){function e(){if(d.apply(a,arguments))return c.apply(a,arguments)}e.fn=c;return e};var ba=document,Ta=ba.documentElement;Z=function(a){return Y(a)||a&&!z(a)&&!a.nodeType&&("undefined"!=typeof window?a!=window:!0)&&!u(a)&&"number"===typeof a.length};var Da=l;N.wrap=function(a,b,c,d){function e(){var a=arguments,b=this;setTimeout(function(){c.apply(b,
a)},d)}u(d)&&(a=d,d=c,c=a);e.fn=c;return e};var ka=q,Ea=k,ja=g.prototype,na=q,ma=k,Ha=g.prototype;L=function(a,b){if(a){var c=arguments;if(z(b))c=ma(arguments,2),b.split(/\s+/).forEach(function(b){la.apply(this,[a,b].concat(c))});else return la.apply(this,c)}};var O="undefined"===typeof jQuery?void 0:jQuery,Fa="undefined"===typeof document?void 0:document,Ga="undefined"===typeof window?void 0:window,Ua={"\u2325":18,alt:18,option:18,backspace:8,capslock:20,caps:20,clear:12,context:93,"\u2318":91,cmd:91,
command:91,"\u2303":17,ctrl:17,control:17,del:46,"delete":46,down:40,end:35,"\u2386":13,enter:13,"return":13,esc:27,escape:27,home:36,insert:45,left:37,pagedown:34,"pg-down":34,pageup:33,"pg-up":33,pause:19,right:39,"\u21e7":16,shift:16,space:32,tab:9,up:38,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,leftmouse:1,rightmouse:3,middlemouse:2,"*":106,"+":107,plus:107,"-":109,minus:109,";":186,semicolon:186,"=":187,equals:187,",":188,dash:189,".":190,"/":191,
"`":192,"~":192,"[":219,"\\":220,"]":221,"'":222},Va=J,oa=l;P.wrap=function(a,b,c,d){if(d)return d=Y(d)?d:z(d)?d.split(/\s*,\s*/):[d],d=d.map(Va),oa.wrap(a,b,c,function(a){for(var b=void 0!==a.which?a.which:a.keyCode,c=d.length;c--;)if(a=d[c],b==a||Ua[a]==b)return!0})};var pa=l,Aa="undefined"!==typeof document?t:null;Q.wrap=function(a,b,c,d){if(Aa){if(u(d)){var e=d;d=c;c=e}return pa.wrap(a,b,c,function(b){b=b.target;return K(a,b)?(b=Aa(b,d))&&K(a,b)?!1:!0:!1})}};var qa=l,Ba="undefined"!==typeof document?
t:null;R.wrap=function(a,b,c,d){if(Ba){if(u(d)){var e=d;d=c;c=e}return qa.wrap(a,b,c,function(b){var c=b.target;if(c!==a&&(c=Ba(c,d))&&a!==c&&K(a,c))return b.delegateTarget=c,!0})}};var ra=l;S.wrap=function(a,b,c,d){function e(){c.apply(a,arguments);r(a,b,e);setTimeout(function(){ra(a,b,e)},d)}if(u(d)){var f=d;d=c;c=f}e.fn=c;return e};var sa=q,Ja=l,Ia=r;C.wrap=function(a,b,c,d){function e(){d(a,b,e);c.apply(a,arguments)}e.fn=c;return e};var Wa=document.documentElement;q={closest:t,parent:function(a,
b){if(!n(a))throw Error("Bad argument "+a);if(a===ba)return Ta;for(;(a=a.parentNode)&&a!==ba;)if(!b||(n(b)?a==b:A(a,b)))return a},prev:function(a,b){if(!n(a))throw Error("Bad argument "+a);for(;a=a.previousSibling;)if(1===a.nodeType&&(!b||(n(b)?a===b:A(a,b))))return a},next:function(a,b){if(!n(a))throw Error("Bad argument "+a);for(;a=a.nextSibling;)if(1===a.nodeType&&(!b||(n(b)?a===b:A(a,b))))return a},root:function(){return Wa}};var Ka=k;t=g.prototype;var w=p.prototype=Object.create(t);w.on=F(l);
w.f=F(C);w.off=F(r);w.c=F(L);p.on=x(l);p.f=x(C);p.off=x(r);p.c=x(L);p.d=x(t.d);p.e=x(t.e);var T=document,V=q,y=Z,Ma=z,La=n,G=B,Xa=ya,wa=!0;try{T.querySelector(":scope")}catch($a){wa=!1}q=function(a,b,c){"string"===typeof a&&(c=b,b=a,a=T);if(!a)return c?[]:null;a=ta(a,b);return!c&&y(a)?a[0]:Xa(a)};var Na=Date.now()%1E9,ca;for(ca in V)q[ca]=V[ca];var E=k,Oa=u,W=z,Qa=Z,Pa=q,xa=B,da;for(da in p)s[da]=p[da];var D=s.prototype=Object.create(p.prototype);D.on=function(a,b,c){Ya(this,a,b,c);return this};D.off=
function(a,b){r(this,a,b);X(this,a,b);return this};D.emit=function(){Za.apply(this,[this].concat(E(arguments)));return this};var ea=new WeakMap,Ya=s.on=function(){H(function(a,b,c){if(c){var d=I(b);b=d[1].split(":")[0];var d=Ra(a,d[1],c),e;(e=ea.get(c))||ea.set(c,e={});(e[b]||(e[b]=[])).push(d);l(a,b,d)}},arguments);return s},X=s.off=function(){H(function(a,b,c){b=I(b)[1].split(":")[0];if(c){if(c=ea.get(c))if(c=c[b])for(var d=c.length;d--;)r(a,b,c[d])}else r(a,b,c)},arguments);return s},Za=s.emit=
function(){H(function(a,b){W(b)&&(b=I(b)[1].split(":")[0]);L.apply(a,[a,b].concat(E(arguments,2)))},arguments);return s},m={};m.on=m.delegate=R.wrap;m.not=Q.wrap;m.pass=m.keypass=P.wrap;m.one=m.once=C.wrap;m.throttle=S.wrap;m.later=N.wrap})();
