(function(){function fa(a,b){if(a)for(var c=z.parse(a+""),d=c[0].split(/\s*,\s*/),e=0;e<d.length;e++)b(z.stringify(d[e],c),e)}function ga(a,b){var c=this===window?document:this;return"string"==typeof a?b?ha.call(c.querySelectorAll(a),0):c.querySelector(a):a instanceof Node||a===window||!a.length?b?[a]:a:ha.call(a,0)}function r(a,b){var c=C.get(a);return b?c&&c[b]||[]:c||{}}function v(a,b,c){if(a){var d,e;if(void 0===c){var f=a.removeAll||a.removeAllListeners;f&&f.call(a,b,c);d=ia(a);if(void 0===b)for(b in d)v(a,
b);else b.split(/\s+/).forEach(function(b){if(d[b])for(var c=d[b].length;c--;)v(a,b,d[b][c])})}else{var p=a.off||a.removeEventListener||a.removeListener;b.split(/\s+/).forEach(function(b){if(p)if(ja.freeze(a,"off"+b))p.call(a,b,c),ja.a(a,"off"+b);else return;b=ia(a,b);for(e=0;e<b.length;e++)if(b[e]===c||b[e].fn===c){b.splice(e,1);break}})}}}function n(a,b,c,d){if(a){var e=a.on||a.addEventListener||a.addListener,f;f=d?n.wrap(c,d):c;b.split(/\s+/).forEach(function(b){if(e)if(ka.freeze(a,"on"+b))e.call(a,
b,f),ka.a(a,"on"+b);else return f;Ca.add(a,b,f,d)});return f}}function D(a,b,c,d){return Da(a,b,D.wrap(a,b,c,d))}function la(a,b,c,d){var e,f=b;a.nodeType||a===Ea||a===Fa?(b instanceof Event?f=b:(f=document.createEvent("CustomEvent"),f.initCustomEvent(b,d,!0,c)),e=a.dispatchEvent):P&&a instanceof P?(f=P.Event(b,c),f.detail=c,e=d?targte.trigger:a.triggerHandler):e=a.emit||a.trigger||a.fire||a.dispatchEvent;var p=Q(arguments,2);if(e&&ma.freeze(a,"emit"+b))e.apply(a,[f].concat(p)),ma.a(a,"emit"+b);else for(e=
Ga(a,f),e=Q(e),f=0;f<e.length;f++)e[f]&&e[f].apply(a,p)}function E(a,b,c,d){return na(a,b,E.wrap(a,b,c,d))}function F(a,b,c,d){return oa(a,b,F.wrap(a,b,c,d))}function A(a,b,c){if(a){var d=a.once||a.one||a.addOnceEventListener||a.addOnceListener,e;e=A.wrap(a,b,c,Ha);b.split(/\s+/).forEach(function(b){if(d&&pa.freeze(a,"one"+b)){var p=d.call(a,b,c);pa.a(a,"one"+b);return p}Ia(a,b,e)});return e}}function G(a,b,c,d){return qa(a,b,G.wrap(a,b,c,d))}function H(a,b,c,d){return ra(a,b,H.wrap(a,b,c,d))}function g(a){if(a){for(var b in s)a[b]=
s[b];return a}}function sa(a,b){if(!b)return w(a)?a:[a];if(a===window)a===[R];else if(!Ja(a)&&!w(a))return[a];b=ta(a,b);var c,d,e=I.parse(b);if(c=/:(parent|closest|next|prev|root)(?:\\([0-9]+))?/.exec(e[0])){d=c[1];var f=c.index,p=I.stringify(e[c[2]],e);c=c[0];f&&(a=ua(a,I.stringify(e[0].slice(0,f),e)));d=S(a,T[d],p);if(!d)return null;if(w(d)&&!d.length)return d;e=I.stringify(e[0].slice(f+c.length).trim(),e);e=ta(d,e);d=sa(d,e)}else d=ua(a,b);return d}function ua(a,b){return w(a)?S(a,function(a,b){return ga.call(a,
b,!0)},b):ga.call(a,b,!0)}function S(a,b,c){var d=[];w(a)||(a=[a]);for(var e=a.length,f;e--;)(f=a[e])&&(f=b(f,c))&&(d=[].concat(f,d));return d}function ta(a,b){if(!Ka(b))return b;b=b.trim();if(!va){if(":scope"===b.slice(0,6))b=b.slice(6);else if(">"!==b[0])return b;var c=(1E9*Math.random()>>>0)+La++;S(a,function(a,b){a.setAttribute("data-__qr",b);return a},c);b='[data-__qr="'+c+'"]'+b}else if(">"===b[0])return":scope "+b;return b}function q(a){if(!a)return a;for(var b in B)a[b]=B[b];return a}function J(a,
b){var c=b[0],d=b[1];Ma(d)||U(c)?(c=null,d=b[0],b=K(b,0)):b=K(b,1);if(d)if(b=K(b,1),d&&"object"===typeof d&&d.constructor===Object)for(var e in d)fa(e,function(b){J(a,[c,b].concat(d[b]))});else U(d)?fa(d,function(d){var e=V(d),h;h=c;e=e[0];h||(h=[document]);h=e?"window"===e?[window]:"document"===e?[document]:Na(h,e,!0):Oa(h)?h:[h];for(var e=0,g=h.length;e<g;e++)a.apply(h[e],[h[e],d].concat(b))}):a.apply(c,[c,d].concat(b))}function V(a){var b=["",""],c=a.match(/[\w\.\:\$\-]+(?:\:[\w\.\:\-\$]+(?:\(.+\))?)*$/)[0];
b[0]=a.slice(0,-c.length).trim();a="on"===c.slice(0,2)?L(c.slice(2)):c;b[1]=a;return b}function Pa(a,b,c){if(c){var d=c,e=wa.parse(b);b=e[0].split(":");var f=b.shift();b.sort(function(a,b){return"once"===a||"one"===a?-1:"once"===b||"one"===b?1:0}).forEach(function(b){var h=b.split("\\");b=h[0];(h=wa.stringify(e[h[1]],e))||(h=function(a,b,d){W(a,b,d);W(a,b,c)});k[b]&&(d=k[b](a,f,d,h))});return d}}window.Emitter=q;var L,t,x,y,M,X,u,xa,m,l,z,N,Y,Z;L=function(a){return a.toLowerCase()};t={freeze:function(a,
b){var c=O.get(a);if(c&&c[b])return!1;c||(c={},O.set(a,c));return c[b]=!0},a:function(a,b){var c=O.get(a);if(!c||!c[b])return!1;c[b]=null;return!0},isFrozen:function(a,b){var c=O.get(a);return c&&c[b]}};var O=new WeakMap;"use strict";l=Element.prototype;var ya=l.matches||l.matchesSelector||l.webkitMatchesSelector||l.mozMatchesSelector||l.msMatchesSelector||l.e;x=function(a,b){if(ya)return ya.call(a,b);for(var c=a.parentNode.querySelectorAll(b),d=0;d<c.length;d++)if(c[d]==a)return!0;return!1};y=function(a){return"string"===
typeof a||a instanceof String};var C=new WeakMap;r.add=function(a,b,c){C.has(a)||C.set(a,{});a=C.get(a);(a[b]=a[b]||[]).push(c)};M=function(a,b){if(a.contains)return a.contains(b);var c=a.compareDocumentPosition(b);return 0===c||c&16};L=function(a){return(a+"").toLowerCase()};X=function(a){return a instanceof Array};var ha=[].slice;u=function(a){return!(!a||!a.apply)};(function(a){function b(a){for(var b=[],c=0;c<a.length;c++)-1===b.indexOf(a[c])&&b.push(a[c]);return b}function c(a){var b=new Set;
return a.filter(function(a){if(!b.has(a))return b.add(a),!0})}function d(a){var b=[];(new Set(a)).forEach(function(a){b.push(a)});return b}function e(){var a=!1;(new Set([!0])).forEach(function(b){a=b});return a}xa="Set"in a?"function"===typeof Set.prototype.forEach&&e()?d:c:b}).call(this,"undefined"!==typeof global?global:"undefined"!==typeof self?self:"undefined"!==typeof window?window:{});m=function(a){return"undefined"!==typeof document&&a instanceof Node};l=l=function(a,b,c){var d=[],e=a.length;
if(0===e)return d;b=0>b?Math.max(0,b+e):b||0;for(void 0!==c&&(e=0>c?c+e:c);e-- >b;)d[e-b]=a[e];return d};var ja=t,ia=r,ka=t,Ca=r;n.wrap=function(a,b,c,d){function e(){if(d.apply(a,arguments))return c.apply(a,arguments)}e.fn=c;return e};z={parse:function(a,b){function c(a){return"\\"+d.push(a.slice(1,-1))}if("string"!==typeof a)return[a];var d=[],e;b=b||"()";for(var f=new RegExp(["\\",b[0],"[^\\",b[0],"\\",b[1],"]*\\",b[1]].join(""));a!=e;)e=a,a=a.replace(f,c);d.unshift(a);return d},stringify:function(a,
b,c){function d(a){return c[0]+b[a.slice(1)]+c[1]}var e;if(!a)return"";"string"!==typeof a&&(c=b,b=a,a=b[0]);for(c=c||"()";a!=e;)e=a,a=a.replace(/\\[0-9]+/,d);return a}};var aa=document,Qa=aa.documentElement;N=function(a,b){if(!m(a))throw Error("Bad argument "+a);if(a===aa)return Qa;if(!b||(m(b)?a==b:x(a,b)))return a;for(;(a=a.parentNode)&&a!==aa;)if(!b||(m(b)?a==b:x(a,b)))return a};var Da=n;D.wrap=function(a,b,c,d){function e(){var a=arguments,b=this;setTimeout(function(){c.apply(b,a)},d)}u(d)&&
(a=d,d=c,c=a);e.fn=c;return e};var ba=document,Ra=ba.documentElement,ma=t,Ga=r,Q=l;Y=function(a,b){if(a){var c=arguments;if(y(b))b.split(/\s+/).forEach(function(b){la.apply(this,[a,b].concat(Q(c,2)))});else return la.apply(this,arguments)}};var P="undefined"===typeof jQuery?void 0:jQuery,Ea="undefined"===typeof document?void 0:document,Fa="undefined"===typeof window?void 0:window;Z=function(a){return X(a)||a&&!y(a)&&!a.nodeType&&("undefined"!=typeof window?a!=window:!0)&&!u(a)&&"number"===typeof a.length};
var Sa={"\u2325":18,alt:18,option:18,backspace:8,capslock:20,caps:20,clear:12,context:93,"\u2318":91,cmd:91,command:91,"\u2303":17,ctrl:17,control:17,del:46,"delete":46,down:40,end:35,"\u2386":13,enter:13,"return":13,esc:27,escape:27,home:36,insert:45,left:37,pagedown:34,"pg-down":34,pageup:33,"pg-up":33,pause:19,right:39,"\u21e7":16,shift:16,space:32,tab:9,up:38,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,leftmouse:1,rightmouse:3,middlemouse:2,"*":106,"+":107,
plus:107,"-":109,minus:109,";":186,semicolon:186,"=":187,equals:187,",":188,dash:189,".":190,"/":191,"`":192,"~":192,"[":219,"\\":220,"]":221,"'":222},Ta=L,na=n;E.wrap=function(a,b,c,d){if(d)return d=X(d)?d:y(d)?d.split(/\s*,\s*/):[d],d=d.map(Ta),na.wrap(a,b,c,function(a){for(var b=void 0!==a.which?a.which:a.keyCode,c=d.length;c--;)if(a=d[c],b==a||Sa[a]==b)return!0})};var oa=n;F.wrap=function(a,b,c,d){function e(){c.apply(a,arguments);v(a,b,e);setTimeout(function(){oa(a,b,e)},d)}if(u(d)){var f=d;
d=c;c=f}e.fn=c;return e};var pa=t,Ia=n,Ha=v;A.wrap=function(a,b,c,d){function e(){d(a,b,e);c.apply(a,arguments)}e.fn=c;return e};var qa=n,za="undefined"!==typeof document?N:null;G.wrap=function(a,b,c,d){if(za){if(u(d)){var e=d;d=c;c=e}return qa.wrap(a,b,c,function(b){b=b.target;return M(a,b)?(b=za(b,d))&&M(a,b)?!1:!0:!1})}};var ra=n,Aa="undefined"!==typeof document?N:null;H.wrap=function(a,b,c,d){if(Aa){if(u(d)){var e=d;d=c;c=e}return ra.wrap(a,b,c,function(b){var c=b.target;if(c!==a&&(c=Aa(c,d))&&
a!==c&&M(a,c))return b.delegateTarget=c,!0})}};var Ua=l,s=g.prototype;s.on=function(a,b,c){n(this,a,b,c);return this};s.once=function(a,b){A(this,a,b);return this};s.off=function(a,b){v(this,a,b);return this};s.emit=function(){Y.apply(this,[this].concat(Ua(arguments)));return this};s.listeners=function(a){return r(this,a)};s.hasListeners=function(a){return!!r(this,a).length};var Va=document.documentElement,R=document,T={closest:N,parent:function(a,b){if(!m(a))throw Error("Bad argument "+a);if(a===
ba)return Ra;for(;(a=a.parentNode)&&a!==ba;)if(!b||(m(b)?a==b:x(a,b)))return a},prev:function(a,b){if(!m(a))throw Error("Bad argument "+a);for(;a=a.previousSibling;)if(1===a.nodeType&&(!b||(m(b)?a===b:x(a,b))))return a},next:function(a,b){if(!m(a))throw Error("Bad argument "+a);for(;a=a.nextSibling;)if(1===a.nodeType&&(!b||(m(b)?a===b:x(a,b))))return a},root:function(){return Va}},w=Z,Ka=y,Ja=m,I=z,Wa=xa,va=!0;try{R.querySelector(":scope")}catch(ab){va=!1}t=function(a,b,c){"string"===typeof a&&(c=
b,b=a,a=R);if(!a)return c?[]:null;a=sa(a,b);return!c&&w(a)?a[0]:Wa(a)};var La=Date.now()%1E9,ca;for(ca in T)t[ca]=T[ca];g.on=function(a,b,c,d){n(a,b,c,d);return this};g.once=function(a,b,c){A(a,b,c);return this};g.off=function(a,b,c){v(a,b,c);return this};g.emit=function(){Y.apply(this,arguments);return this};g.delegate=function(a,b,c,d){H(a,b,c,d);return this};g.later=function(a,b,c,d){D(a,b,c,d);return this};g.keypass=function(a,b,c,d){E(a,b,c,d);return this};g.throttle=function(a,b,c,d){F(a,b,
c,d);return this};g.not=function(a,b,c,d){G(a,b,c,d);return this};g.listeners=r;g.hasListeners=function(a,b){return!!r(a,b).length};var K=l,Ma=u,U=y,Oa=Z,Na=t,wa=z,Xa=g.on,Ba=g.off,Ya=g.b,da;for(da in g)q[da]=g[da];var B=q.prototype=Object.create(g.prototype);B.on=function(){return Za.apply(this,arguments)};B.off=function(){return W.apply(this,arguments)};B.emit=function(){return $a.apply(this,arguments)};var ea=new WeakMap,Za=q.on=function(){J(function(a,b,c){if(c){var d=V(b);b=d[1].split(":")[0];
var d=Pa(a,d[1],c),e;(e=ea.get(c))||ea.set(c,e={});(e[b]||(e[b]=[])).push(d);Xa(a,b,d)}},arguments);return q},W=q.off=function(){J(function(a,b,c){b=V(b)[1].split(":")[0];if(c){if(c=ea.get(c))if(c=c[b])for(var d=c.length;d--;)Ba(a,b,c[d])}else Ba(a,b,c)},arguments);return q},$a=q.emit=function(){J(function(a,b){U(b)&&(b=b.split(":")[0]);Ya.apply(a,[a,b].concat(K(arguments,2)))},arguments);return q},k={};k.on=k.delegate=H.wrap;k.not=G.wrap;k.h=k.c=E.wrap;k.one=k.f=A.wrap;k.i=F.wrap;k.d=D.wrap;k.g=
["one","once"]})();
